version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,sns,sqs
      - DEFAULT_REGION=us-east-1
      
    

  auth-service:
    build: ./services/1-auth-service
    container_name: auth-service
    ports:
      - "3001:3000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=Users
      - JWT_SECRET=your-super-secret-key-for-local-dev
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    volumes:
      - ./services/1-auth-service:/app

  room-booking-service:
    build: ./services/2-room-booking-service
    container_name: room-booking-service
    ports:
      - "3002:3000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=Bookings
      - DYNAMODB_ROOMS_TABLE_NAME=Rooms
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:SmartOfficeBookingEvents_Local
      - JWT_SECRET=your-super-secret-key-for-local-dev
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - SNS_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    volumes:
      - ./services/2-room-booking-service:/app

  desk-booking-service:
    build: ./services/3-desk-booking-service
    container_name: desk-booking-service
    ports:
      - "3003:3000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=Bookings
      - DYNAMODB_DESKS_TABLE_NAME=Desks
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:SmartOfficeBookingEvents_Local
      - JWT_SECRET=your-super-secret-key-for-local-dev
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - SNS_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    volumes:
      - ./services/3-desk-booking-service:/app

  


