version: '3.8'

services:
  auth-service:
    build: ./services/1-auth-service
    container_name: auth-service
    ports:
      - "3001:3000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=Users
      - JWT_SECRET=your-super-secret-key-for-local-dev
      # For local DynamoDB
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    volumes:
      - ./services/1-auth-service:/app

  room-booking-service:
    build: ./services/2-room-booking-service
    container_name: room-booking-service
    ports:
      - "3002:3000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=Bookings
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:SmartOfficeBookingEvents_Local
      - JWT_SECRET=your-super-secret-key-for-local-dev
      # For local DynamoDB
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    volumes:
      - ./services/2-room-booking-service:/app

  desk-booking-service:
    build: ./services/3-desk-booking-service
    container_name: desk-booking-service
    ports:
      - "3003:3000"
    environment:
      - AWS_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=Bookings
      - SNS_TOPIC_ARN=arn:aws:sns:us-east-1:000000000000:SmartOfficeBookingEvents_Local
      - JWT_SECRET=your-super-secret-key-for-local-dev
      # For local DynamoDB
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    volumes:
      - ./services/3-desk-booking-service:/app

  notification-service:
    build: ./services/4-notification-service
    container_name: notification-service
    environment:
      - AWS_REGION=us-east-1
      - SQS_QUEUE_URL=http://localhost:4566/000000000000/NotificationQueue_Local
      # For local SQS (if using with LocalStack, etc.)
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - ./services/4-notification-service:/app

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8001:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data:
